name: csst
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314hf8a3a22_4
  - cpython=3.14.3=py314hd8ed1ab_101
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.20=py314he609de1_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=hce30654_0
  - icu=78.2=h38cb7af_0
  - ipykernel=7.2.0=pyh5552912_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py314h42813c9_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libmpdec=4.0.0=h84a0fba_1
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.55=h132b30e_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - matplotlib=3.10.8=py314he55896b_0
  - matplotlib-base=3.10.8=py314hd63e3f0_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - matplotlib-label-lines=0.7.0=pyhd8ed1ab_1
  - more-itertools=10.8.0=pyhcf101f3_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.2=py314hae46ccb_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py314h5e21a50_0
  - parso=0.8.6=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.1=py314hab283cf_0
  - pip=26.0.1=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py314ha14b1ff_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.14.3=h4c637c5_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.3=h4df99d1_101
  - python_abi=3.14=8_cp314
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - qutip=5.2.3=py314h2a1ed3d_0
  - readline=8.3=h46df422_0
  - scikit-learn=1.8.0=np2py314h15f0f0f_1
  - scipy=1.17.0=py314hfc1f868_1
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py314hdcf55e8_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h010d191_3
  - tornado=6.5.4=py314h0612a62_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py314h0612a62_1
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zeromq=4.3.5=h888dc83_9
  - zlib-ng=2.3.3=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/joey/miniconda3/envs/csst
