name: shadows
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - clarabel=0.11.1=py313h44a41ba_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hc50a443_2
  - cpython=3.13.7=py313hd8ed1ab_100
  - cvxpy=1.7.2=py313h39782a4_0
  - cvxpy-base=1.7.2=py313hd1f53c0_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.60.0=py313h7d74516_0
  - freetype=2.14.1=hce30654_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.9=py313hf88c9ab_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=35_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=35_hb0561ab_openblas
  - libcxx=21.1.1=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=35_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libosqp=1.0.0=np2py313hd6693e2_2
  - libpng=1.6.50=h280e0eb_1
  - libqdldl=0.1.8=ha1acc90_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=h025e3ab_6
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.0=hbb9b287_0
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib=3.10.6=py313h39782a4_1
  - matplotlib-base=3.10.6=py313h58042b9_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.3=py313h9771d21_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.4=h5503f6c_0
  - osqp=1.0.5=np2py313h9ce8dcc_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py313hd1f53c0_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313he4c6d0d_3
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h6535dbc_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.4=pyhcf101f3_0
  - python=3.13.7=h5c937ed_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.7=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qdldl-python=0.1.7.post5=np2py313h9ce8dcc_3
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - scienceplots=2.1.1=pyhd8ed1ab_1
  - scikit-learn=1.7.2=py313h6eea1c5_0
  - scipy=1.16.2=py313h0d10b07_0
  - scs=3.2.9=default_py313h120b7a5_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313h46657e6_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py313hcdf3177_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - idna==3.10
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - matplotlib-label-lines==0.8.1
      - more-itertools==10.8.0
      - msgpack==1.1.1
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pyyaml==6.0.3
      - qutip==5.2.1
      - ray==2.49.2
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - tensorboardx==2.6.4
      - urllib3==2.5.0
prefix: /Users/joey/miniconda3/envs/shadows
